// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Zu_tOc-cz-hMnOaLTvomiQupORtNTLQ',
    appId: '1:1047597209614:web:9dbb272049d4a0c9eb445f',
    messagingSenderId: '1047597209614',
    projectId: 'assent-social-media-app',
    authDomain: 'assent-social-media-app.firebaseapp.com',
    storageBucket: 'assent-social-media-app.appspot.com',
    measurementId: 'G-KJ1SLLCWTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHZDJvg3uhpoNFs0vM3mz_BdGc-aTUimQ',
    appId: '1:1047597209614:android:97716205b6473a4feb445f',
    messagingSenderId: '1047597209614',
    projectId: 'assent-social-media-app',
    storageBucket: 'assent-social-media-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHi2GOvwnX8-Hc2PxMcAY3lDVoXZGMr3s',
    appId: '1:1047597209614:ios:004d0a53613bc004eb445f',
    messagingSenderId: '1047597209614',
    projectId: 'assent-social-media-app',
    storageBucket: 'assent-social-media-app.appspot.com',
    androidClientId: '1047597209614-elq3s0ebckal5pfdoht6ekmst9ltvved.apps.googleusercontent.com',
    iosClientId: '1047597209614-231rqmrjhgacu9btmvcrbvprbg8kgnfu.apps.googleusercontent.com',
    iosBundleId: 'com.assentsocialmediapp.firebase.socialMediaApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHi2GOvwnX8-Hc2PxMcAY3lDVoXZGMr3s',
    appId: '1:1047597209614:ios:3d40de340d6fa7f4eb445f',
    messagingSenderId: '1047597209614',
    projectId: 'assent-social-media-app',
    storageBucket: 'assent-social-media-app.appspot.com',
    androidClientId: '1047597209614-elq3s0ebckal5pfdoht6ekmst9ltvved.apps.googleusercontent.com',
    iosClientId: '1047597209614-ej7n2ct4828amk4p5r9focqb7sigl4tq.apps.googleusercontent.com',
    iosBundleId: 'com.assentsocialmediapp.firebase.socialMediaApplication.RunnerTests',
  );
}
